const CATALOG = [
    {
        id: 'el1',
        name: 'Woody melody',
        img: 'img/catalog/catalog-img-1.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'brown',
        price: 72580,
    },
    {
        id: 'el2',
        name: 'White absolute',
        img: 'img/catalog/catalog-img-2.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'white',
        price: 92000,
    },
    {
        id: 'el3',
        name: 'Harmony beige',
        img: 'img/catalog/catalog-img-3.jpg',
        type: 'Распашной шкаф',
        size: '230*150*250',
        material: 'МДФ',
        color: 'beige',
        price: 120000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
    //повтор
    {
        id: 'el1',
        name: 'Woody melody',
        img: 'img/catalog/catalog-img-1.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'brown',
        price: 72580,
    },
    {
        id: 'el2',
        name: 'White absolute',
        img: 'img/catalog/catalog-img-2.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'white',
        price: 92000,
    },
    {
        id: 'el3',
        name: 'Harmony beige',
        img: 'img/catalog/catalog-img-3.jpg',
        type: 'Распашной шкаф',
        size: '230*150*250',
        material: 'МДФ',
        color: 'beige',
        price: 120000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
    {
        id: 'el1',
        name: 'Woody melody',
        img: 'img/catalog/catalog-img-1.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'brown',
        price: 72580,
    },
    {
        id: 'el2',
        name: 'White absolute',
        img: 'img/catalog/catalog-img-2.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'white',
        price: 92000,
    },
    {
        id: 'el3',
        name: 'Harmony beige',
        img: 'img/catalog/catalog-img-3.jpg',
        type: 'Распашной шкаф',
        size: '230*150*250',
        material: 'МДФ',
        color: 'beige',
        price: 120000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
    {
        id: 'el1',
        name: 'Woody melody',
        img: 'img/catalog/catalog-img-1.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'brown',
        price: 72580,
    },
    {
        id: 'el2',
        name: 'White absolute',
        img: 'img/catalog/catalog-img-2.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'white',
        price: 92000,
    },
    {
        id: 'el3',
        name: 'Harmony beige',
        img: 'img/catalog/catalog-img-3.jpg',
        type: 'Распашной шкаф',
        size: '230*150*250',
        material: 'МДФ',
        color: 'beige',
        price: 120000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
];