const CATALOG = [
    {
        id: 'el1',
        name: 'Woody melody',
        img: 'img/catalog/catalog-img-1.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'brown',
        price: 72580,
    },
    {
        id: 'el2',
        name: 'White absolute',
        img: 'img/catalog/catalog-img-2.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'ДСП',
        color: 'white',
        price: 92000,
    },
    {
        id: 'el3',
        name: 'Harmony beige',
        img: 'img/catalog/catalog-img-3.jpg',
        type: 'Распашной шкаф',
        size: '230*150*250',
        material: 'МДФ',
        color: 'beige',
        price: 120000,
    },
    {
        id: 'el4',
        name: 'Warm stone',
        img: 'img/catalog/catalog-img-4.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gray',
        price: 73000,
    },
    {
        id: 'el5',
        name: 'Golden melody',
        img: 'img/catalog/catalog-img-5.jpg',
        type: 'Шкаф-купе',
        size: '230*150*250',
        material: 'МДФ',
        color: 'gold',
        price: 150000,
    },
    {
        id: 'el6',
        name: 'Black G520',
        img: 'img/catalog/catalog-img-6.jpg',
        type: 'Шкаф-купе',
        size: '60*120*140',
        material: 'МДФ',
        color: 'black',
        price: 150000,
    },
    {
        id: 'el7',
        name: 'Gray G520',
        img: 'img/catalog/catalog-img-7.jpg',
        type: 'Шкаф-купе',
        size: '60*120*140',
        material: 'МДФ',
        color: 'gray',
        price: 150000,
    },
    {
        id: 'el8',
        name: 'Classic model',
        img: 'img/catalog/catalog-img-8.jpg',
        type: 'Распашной шкаф',
        size: '60*120*140',
        material: 'ДСП',
        color: 'beige',
        price: 150000,
    },
    {
        id: 'el9',
        name: 'Wardrobe white',
        img: 'img/catalog/catalog-img-9.jpg',
        type: 'Гардеробная',
        size: '60*120*140',
        material: 'ДСП',
        color: 'white',
        price: 150000,
    },
];